# Generated by Django 2.1.1 on 2018-09-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='Mark',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='testdata',
            name='Math',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='testdata',
            name='RollNo',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
