# Generated by Django 2.1.1 on 2018-09-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlogTest', models.IntegerField(blank=True, max_length=50, null=True, unique=True)),
                ('BloggerName', models.CharField(max_length=50, null=True, unique=True)),
                ('BloggerContactNo', models.CharField(max_length=50, null=True, unique=True)),
                ('EmpDOJ', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
    ]
