# Generated by Django 2.1.1 on 2018-09-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20180928_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtestdata',
            name='BloggerName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
